# Generated by Django 3.2 on 2021-07-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='contenido',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='position',
            field=models.CharField(choices=[('HM', 'HOME_MAIN'), ('BM', 'BOTTOM_MAIN'), ('TM', 'TOP_MAIN')], default='TM', max_length=50),
        ),
        migrations.AddField(
            model_name='articulos',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
