# Generated by Django 3.2 on 2021-07-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20210715_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='artfile',
            new_name='art_archivo',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='position',
            new_name='posicion',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='pub_date',
            new_name='pub_fecha',
        ),
    ]
