# Generated by Django 3.2 on 2021-07-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20210715_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='contenido',
            new_name='resumen',
        ),
    ]
