# Generated by Django 3.2 on 2021-07-16 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0013_delete_articulos'),
        ('articulos', '0005_articulos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='cuentas.categorias'),
        ),
    ]
