# Generated by Django 3.2 on 2021-07-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_rename_date_modified_perfiles_data_modificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion de bigrafia'),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('s', 'Soltero'), ('c', 'Casado'), ('d', 'Divorciado'), ('v', 'Viudo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='gener',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1, null=True, verbose_name='Genro'),
        ),
    ]
