# Generated by Django 3.2 on 2021-07-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_auto_20210703_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='fecNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
