# Generated by Django 3.2 on 2021-07-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_alter_perfiles_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='foto',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='media', verbose_name='Foto de perfil', width_field=200),
        ),
    ]
