# Generated by Django 3.2 on 2021-07-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_articulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='artfile',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
