# Generated by Django 3.2 on 2021-07-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_articulos_artfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='artfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
