# Generated by Django 3.2 on 2021-07-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_alter_articulos_artfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulos',
        ),
    ]
