# Generated by Django 3.2 on 2021-07-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0017_alter_comentarios_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='text',
            new_name='comentario',
        ),
    ]
