# Generated by Django 3.2 on 2021-07-26 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0019_auto_20210726_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios_articulo',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='comentarios_publicacion',
            name='articulo',
        ),
        migrations.AddField(
            model_name='comentarios_articulo',
            name='articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuentas.articulos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentarios_publicacion',
            name='publicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuentas.publicaciones'),
            preserve_default=False,
        ),
    ]
