# Generated by Django 3.2 on 2021-07-26 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0021_alter_comentarios_articulo_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios_articulo',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.comentarios_articulo'),
        ),
    ]
