# Generated by Django 3.2 on 2021-07-26 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0022_alter_comentarios_articulo_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='art_archivo',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='comentarios_articulo',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cuentas.comentarios_articulo'),
        ),
    ]
