# Generated by Django 3.2.2 on 2021-07-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0024_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
