# Generated by Django 3.2.2 on 2021-07-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0025_delete_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
