# Generated by Django 3.2.2 on 2021-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0026_alter_articulos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
