# Generated by Django 3.2.2 on 2021-07-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0028_auto_20210730_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='estatus',
            field=models.CharField(choices=[('f', 'Usuario destacado'), ('c', 'Creador de contenido'), ('u', 'Usuario nuevo')], default='u', max_length=1, verbose_name='Estatus'),
        ),
    ]
