# Generated by Django 3.2.2 on 2021-07-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0030_auto_20210730_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Foto de perfil'),
        ),
    ]
