# Generated by Django 3.2.2 on 2021-07-31 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0032_auto_20210731_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios_publicacion',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.articulos'),
        ),
    ]
