# Generated by Django 3.2.2 on 2021-08-02 04:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0034_alter_articulos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.FileField(default='settings.MEDIA_ROOT/media/anonimo.png', storage=django.core.files.storage.FileSystemStorage(location='/home/andrew/workspaceSoftware/programasWeb/SoftDatosAdoles/src/Backend/media'), upload_to='media/'),
        ),
    ]
