# Generated by Django 3.2.2 on 2021-08-02 04:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0035_alter_articulos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='articulos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='foto',
            field=models.FileField(default='settings.MEDIA_ROOT/media/anonimo.png', storage=django.core.files.storage.FileSystemStorage(location='/home/andrew/workspaceSoftware/programasWeb/SoftDatosAdoles/src/Backend/media'), upload_to='media/'),
        ),
    ]
