# Generated by Django 3.2.2 on 2021-08-02 04:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0036_auto_20210801_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='foto',
            field=models.FileField(default='media/media/anonimo.png', storage=django.core.files.storage.FileSystemStorage(location='/home/andrew/workspaceSoftware/programasWeb/SoftDatosAdoles/src/Backend/media'), upload_to='media/'),
        ),
    ]
