# Generated by Django 3.2.2 on 2021-08-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0038_alter_perfiles_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField(auto_now=True)),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.comentarios_publicacion')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.perfiles')),
            ],
        ),
    ]
