# Generated by Django 3.2.2 on 2021-08-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0040_comentarios_publicacion_numero_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reacciones',
            old_name='id_comentario',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='reacciones',
            old_name='id_perfil',
            new_name='perfil',
        ),
    ]
