# Generated by Django 3.2.2 on 2021-08-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0041_auto_20210802_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios_publicacion',
            name='numero_likes',
        ),
    ]
